name: "pace main unit tests"

# Run these these whenever ...
on:
  workflow_call: # ... called from a downstream repo
    inputs:
      component_trigger:
        type: boolean
        default: false
        required: false
      component_name:
        type: string
        default: ''
        required: false
      python_version:
        type: string
        default: ''
        required: false
  pull_request: # ... a PR is opened / updated
  merge_group:  # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pace_main_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Dummy step"
        run: echo "Hi there! 👋"
